#!/usr/bin/env bash

set -euo pipefail

test=
force=
while getopts ':tf' opt; do
  case "$opt" in
    t)
      test=true
      ;;

    f)
      force=true
      ;;

    '?')
      >&2 printf 'Invalid option: -%s\n' "$OPTARG"
      exit 1
      ;;
  esac
done

code='US'
latest_release="https://data.services.jetbrains.com/products/releases?code=$code&latest=true"
version_query="[.${code}[0].version, .${code}[0].build] | join(\".\")"
notes_query=".${code}[0].notesLink"

json="$(curl --silent --show-error "$latest_release")"
latest="$(jq --raw-output --exit-status "$version_query" <<< "$json")"
current="$(sed -ne 's/ARG VERSION=//p' Dockerfile)"
if ! notes="$(jq --raw-output --exit-status "$notes_query" <<< "$json")"; then
  >&2 printf 'No release notes for version %s\n' "$latest"
  notes=
fi

if [[ "$current" == "$latest" ]]; then
  printf '%s is still the latest release\n' "$current"
  [[ -z "$force" ]] && exit
fi

if [[ -n "$test" ]]; then
  printf 'Testing docker build with version %s\n' "$latest"

  if ! docker image build --label "test-build=$code" \
                          --force-rm \
                          --build-arg "VERSION=$latest" \
                          .; then
    exit 2
  fi

  docker image ls --quiet \
                  --filter "label=test-build=$code" |
    xargs --no-run-if-empty docker image rm
fi

printf 'Updating Dockerfile from version %s to version %s\n' "$current" "$latest"
sed -i "s/\(ARG VERSION=\).*/\1$latest/" Dockerfile

if [[ -n "$notes" ]]; then
  message="$(printf 'Update to %s\n\nRelease notes: %s\n' "$latest" "$notes")"
else
  message="$(printf 'Update to %s\n' "$latest")"
fi
git commit --message "$message" \
           -- \
           Dockerfile

git tag "$latest"
